### ISSUE TITLE
cargo build not working

### ISSUE THREAD

**Issue by michg** [mcobzarenco/zee#5]
Hello Marius,
thanks for your editor. Currently the build seems to be broken. Core/Cargo.toml references a local version of zi:
zi = { version = "0.1.4", path = "../../zi" } 
With the tagged version 0.1.4 of zi, it does not build:

error[E0599]: no method named `invert` found for struct `Style` in the current scope
   --> core\src\components\prompt\buffers.rs:288:65
    |
288 | ...                   .style(self.properties.theme.action.invert())
    |                                                           ^^^^^^ method not found in `Style`

error[E0599]: no function or associated item named `new` found for struct `Container` in the current scope
   --> core\src\editor.rs:578:40
    |
578 |         let mut container = Container::new(FlexDirection::Row);
    |                                        ^^^ function or associated item not found in `Container`

error[E0599]: no function or associated item named `new` found for struct `Container` in the current scope
   --> core\src\editor.rs:593:44
    |
593 |                     container = Container::new(*direction);
    |                                            ^^^ function or associated item not found in `Container`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `zee`

Regards,
Michael

**Comment by mcobzarenco** [comment]
Thanks for this Michael and my apologies for slow reply and broken master -- will fix asap

**Comment by michg** [comment]
Thanks a lot for fixing it,  the new version looks good.
Regards,
Michael
